### ISSUE TITLE
Material Icons: React icon issue

### ISSUE THREAD

**Issue by MdSakifHossain** [sebastianjnuwu/acode-theme-vscode#19]
Can you please add the "react" icon for jsx and tsx.
It doesn't show any react icon.
Thank you in advance sir... ✨😊

**Comment by sebastianjnuwu** [comment]
https://acode.app/plugin/sebastianjnuwu.material.icons

**Comment by sebastianjnuwu** [comment]
Hi, “Material Icons” already has these icons!

Could it be more specific which plugin are you using, FREE or PAID?

**Comment by MdSakifHossain** [comment]
I'm using the "Material Icons" plugin.
What do you mean by Free or Paid?
It's the free version.

There's every icon.
But, react's icon is not showing.
I'm getting the same js icon. 🥲

It's kinda painful 😣

**Comment by sebastianjnuwu** [comment]
The "material icons" plugin already has these icons, as I said before, try reinstalling the plugin! If you have other icon plugins uninstalled, there may be conflicts! 

If it's not too much trouble, can you send a photo of the plugins you are using?

**Comment by sebastianjnuwu** [comment]
> O plugin "material icons" já possui esses ícones, como falei antes, tente reinstalar o plugin! Se você tiver outros plug-ins de ícones desinstalados, pode haver conflitos!
> 
> Se não for muito incômodo, você pode enviar uma foto dos plugins que está usando?

![Screenshot_20240314-153302~2](https://github.com/sebastianjnuwu/acode-plugins/assets/101356556/fcf15e0f-be08-4338-a5da-7e10d59ecfde)

**Comment by MdSakifHossain** [comment]
I have reinstalled it.
Just for the first time, React icon was showing.
But, after closing and reopening Acode, there were no react icon.
Just the same old js icon. 🥲

I have done everything again like you said. Yet, it's still not working.

It just happens all the time.
There are React icon after installing your plug-in.
But, if I close Acode and then I reopen Acode...
The React icon is replaced by js icon. 😐😕

I hope you can understand what's happening and can fix this issue.

Thank you in advance for your precious time. 🫂

**Comment by sebastianjnuwu** [comment]
"I'm not finding anything that could cause an error! That's really strange. Could you send me screenshots or a video of your project plus plugins? It would be easier. Also, download 'Eruda' to see if it logs any errors. I'm waiting for your response! Hopefully, we can solve this issue!"

**Comment by MdSakifHossain** [comment]
Is there any social media you use??

I don't use e-mail services very well..
Haven't used since now.
I'm so sorry for wasting your time. 😔


I use telegram though.
This is my telegram account.
You can use telegram on your browser without installing on your PC. 😅

*********

**Comment by sebastianjnuwu** [comment]
Sorry I don't use Telegram, if you access github by clicking here you can send images and videos, without this data I don't know what I can do. until update 1.10.0 (944) the plugin works

**Comment by sebastianjnuwu** [comment]
Sorry I don't use Telegram, if you access github by clicking [here](https://github.com/sebastianjnuwu/acode-plugins/issues/19) you can send images and videos, without this data I don't know what I can do. until update 1.10.0 (944) the plugin works.

**Comment by MdSakifHossain** [comment]
Here are the screenshots you asked.
Sorry I was kinda busy with my family.
![Screenshot_2024-03-15-22-44-14-97_a2cf8efcdd42a8e6f7906303f104fb67](https://github.com/sebastianjnuwu/acode-plugins/assets/105617508/191280eb-dce3-47e1-9f4e-1b69bae8dc1a)
![Screenshot_2024-03-15-22-44-07-66_a2cf8efcdd42a8e6f7906303f104fb67](https://github.com/sebastianjnuwu/acode-plugins/assets/105617508/a1c05bd3-fde2-4c79-84f7-eb0f1a3be571)

But, I didn't get it where you said "eruda" what is that sir?
