### ISSUE TITLE
Need improvement in Material Icon 

### ISSUE THREAD

**Issue by bajrangCoder** [sebastianjnuwu/acode-theme-vscode#2]
Instead of loading icons from GitHub, load it locally so it will work in offline mode too.
Put your icons in `dist` folder and scss file access like this: `this.baseUrl+"youricon.svg"`
And make sure to include your icons in plugin.json files array.

**Comment by sebastianjnuwu** [comment]
> Instead of loading icons from GitHub, load it locally so it will work in offline mode too. Put your icons in `dist` folder and scss file access like this: `this.baseUrl+"youricon.svg"` And make sure to include your icons in plugin.json files array.

Still awake? My idea was to leave it locally even though I couldn't import the icons in the dist folder using plugin.json: ` "files": ["icons/*"], "files": ["icons/*.svg"]` I tried both ways I couldn't can you tell me how to do it! About `this.baseUrl+"youricon.svg"` Change the scss url()? I didn't understand right

**Comment by bajrangCoder** [comment]
> > Instead of loading icons from GitHub, load it locally so it will work in offline mode too. Put your icons in `dist` folder and scss file access like this: `this.baseUrl+"youricon.svg"` And make sure to include your icons in plugin.json files array.
> 
> Still awake? My idea was to leave it locally even though I couldn't import the icons in the dist folder using plugin.json: ` "files": ["icons/*"], "files": ["icons/*.svg"]` I tried both ways I couldn't can you tell me how to do it! About `this.baseUrl+"youricon.svg"` Change the scss url()? I didn't understand right

You can't do like that you will need to define every icons file in plugin.json files array
Like this:
```js
files: [
  "icons/1.svg",
  "icons/2.svg",
  And so on...
]
```

Inside your scss replace GitHub icon url to this:
`this.baseUrl + "icons/1.svg"`

**Comment by sebastianjnuwu** [comment]
> > > Instead of loading icons from GitHub, load it locally so it will work in offline mode too. Put your icons in `dist` folder and scss file access like this: `this.baseUrl+"youricon.svg"` And make sure to include your icons in plugin.json files array.
> > 
> > 
> > Still awake? My idea was to leave it locally even though I couldn't import the icons in the dist folder using plugin.json: ` "files": ["icons/*"], "files": ["icons/*.svg"]` I tried both ways I couldn't can you tell me how to do it! About `this.baseUrl+"youricon.svg"` Change the scss url()? I didn't understand right
> 
> You can't do like that you will need to define every icons file in plugin.json files array Like this:
> 
> ```js
> files: [
>   "icons/1.svg",
>   "icons/2.svg",
>   And so on...
> ]
> ```
> 
> Inside your scss replace GitHub icon url to this: `this.baseUrl + "icons/1.svg"`

the icons are not going to the dist folder, and the error sass with this "+" `this.baseUrl + "icons/1.svg"`

I can test it there to see if it works and I will be grateful I think it must be my mistake: `git clone -b <branch> <url>`

**Comment by bajrangCoder** [comment]
You can take refrence from here : https://github.com/bajrangCoder/acode-ayu-mirage-theme

**Comment by sebastianjnuwu** [comment]
@bajrangCoder The plugin has been fixed now there is offline availability, we added some new icons as well that acode didn't have!
