### ISSUE TITLE
Update Acode Eruda Plugin's Eruda Console to the latest Version 

### ISSUE THREAD

**Issue by UnschooledGamer** [sebastianjnuwu/acode-theme-vscode#33]
It's 4 minor version behind (Plugin has `v3.0.1`) Whereas latest is `3.4.1`.

https://www.npmjs.com/package/eruda

@sebastianjnuwu

**Comment by sebastianjnuwu** [comment]
Ok

**Comment by sebastianjnuwu** [comment]
I'm encountering errors when importing this version.

**Comment by sebastianjnuwu** [comment]
@UnschooledGamer Can you also try to fix it and send a PR? 

https://github.com/sebastianjnuwu/acode-plugins/blob/c2ce7f64a61305d0b03d1d9b6428f9f1afa0f5f5/plugin/acode-eruda/src/main.js

**Comment by UnschooledGamer** [comment]
> @UnschooledGamer Can you also try to fix it and send a PR? 
> 
> https://github.com/sebastianjnuwu/acode-plugins/blob/c2ce7f64a61305d0b03d1d9b6428f9f1afa0f5f5/plugin/acode-eruda/src/main.js

I'll try to do so. In my free time.

**Comment by sebastianjnuwu** [comment]
https://github.com/sebastianjnuwu/acode-plugins/tree/acode/packages/acode-eruda

**Comment by UnschooledGamer** [comment]
> https://github.com/sebastianjnuwu/acode-plugins/tree/acode/packages/acode-eruda

Is it done?

**Comment by sebastianjnuwu** [comment]
> > https://github.com/sebastianjnuwu/acode-plugins/tree/acode/packages/acode-eruda
> 
> Is it done?

No, it's failing. Why, I don't know!

**Comment by sebastianjnuwu** [comment]
Solved! Thanks for your contribution!
